-- begin GANTTDEMO_TASK
alter table GANTTDEMO_TASK add constraint FK_GANTTDEMO_TASK_PARENT foreign key (PARENT_ID) references GANTTDEMO_TASK(ID)^
create index IDX_GANTTDEMO_TASK_PARENT on GANTTDEMO_TASK (PARENT_ID)^
-- end GANTTDEMO_TASK
